AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lamda local demo

Resources:
  LambdaJokes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ # format is projectPath/
      Handler: lambdajokes.handler # format is filename.functionName
      Runtime: nodejs12.x
